import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-red-500 p-5 flex justify-between">
          <h2>Navbar</h2>
          <ul className="flex gap-4">
            <li>Home</li>
            <li>Home</li>
            <li>Home</li>
          </ul>
        </div>
        {children}
        <div className="bg-red-500 p-5 flex justify-between">
          <ul className="flex gap-4">
            <li>Home</li>
            <li>Home</li>
            <li>Home</li>
          </ul>
          Footer
          <ul className="flex gap-4">
            <li>Home</li>
            <li>Home</li>
            <li>Home</li>
          </ul>
        </div>
      </body>
    </html>
  );
}
